### PR TITLE
fix: Use Authorization header for sending access_token to WebSocket API

### LINKED ISSUE #1248: Sends access token via Sec-Websocket-Protocol header
masto.js sends the access token for the streaming API via the `Sec-Websocket-Protocol` header. The [Mastodon documentation of the streaming API](https://docs.joinmastodon.org/methods/streaming/#websocket) does not document this way of use. Also this header is not considered sensitive, so often logged. Worse, the whole header is copied in the response, with another chance of it being logged.

The documented way to do auth against the streaming API is to use the `access_token` query parameter. Which is another level of problem, but this is understood.

The standard `Authorization` header is [implemented as well](https://github.com/mastodon/mastodon/blob/main/streaming/index.js#L382) for the streaming API, but not documented.

See https://github.com/mastodon/documentation/issues/1575

### PR DESCRIPTION
**Pull request by neet**
Closes #1248

### CODE REVIEW

File: src/adapters/config/web-socket-config.ts [hunk 1]
```diff
@@ -59,15 +59,17 @@ export class WebSocketConfigImpl implements WebSocketConfig {
...
       this.props.useInsecureAccessToken ||
       this.props.accessToken == undefined
     ) {
-      return [...protocols];
+      return {};
     }
 
-    return [this.props.accessToken, ...protocols];
+    return {
+      Authorization: this.props.accessToken,
```
Comment (waldiTM) [inline src/adapters/config/web-socket-config.ts:71]: This is wrong. The `Authorization` header requires the type, which is `Bearer`. So:

```
Authorization: `Bearer ${this.props.accessToken}`,
```

Comment (neet) [reply src/adapters/config/web-socket-config.ts:71]: Oh thank you for having a look, I'm fixing it in #1259
