### PR TITLE
Pagination params fix

### LINKED ISSUE #698: maxId in DefaultPaginationParams should be able to be set externally
https://github.com/neet/masto.js/blob/ebdaee852af4121cb9db679b1d925327c21f15cc/src/repositories/repository.ts#L1-L10

There is no way to reverse the pagination direction of [`/api/v1/accounts/:id/statuses`](https://docs.joinmastodon.org/methods/accounts/#statuses), making the ability to set the `max_id` parameter necessary to create a resumable application that downloads all of someone's statuses.

If an end user does manually set `maxId`, their `AsyncIterable` will get caught in an endless loop due to Masto setting the `max_id` parameter twice (in fact, everything's repeated): `https://pony.social/api/v1/accounts/106500315995032015/statuses?exclude_replies=false&exclude_replies=false&limit=100&limit=100&max_id=109323073972972141&max_id=109332395072165340&pinned=false&pinned=false`. Seeing as `max_id` isn't an internal detail of the Mastodon API (it's actually older than `min_id`), users should be able to set it without running into issues like I did.

Also, `maxId` doens't properly handle a `null` input; instead of not including the `max_id` parameter, it sends `max_id=null`, which Mastodon doesn't understand.

### PR DESCRIPTION
**Pull request by SuperSonicHub1**
Fixes #698.

### CODE REVIEW

File: src/paginator.ts [hunk 1]
```diff
@@ -37,6 +37,7 @@ export class Paginator<Params, Result>
       typeof response.headers?.link === 'string'
         ? this.pluckNext(response.headers.link)
         : undefined;
+    this.nextParams = {};
```
Comment (neet) [inline src/paginator.ts:40]: Typecheck seems to be failing. You can just add downcasting such as `{} as Params` for now

Comment (SuperSonicHub1) [reply src/paginator.ts]: Fixed.
