### PR TITLE
Fix the type of Filter.wholeWorld to boolean

### LINKED ISSUE #725: Filter interface needs update
Checking the docs for Filter [here](https://docs.joinmastodon.org/methods/filters/#200-ok) I see some props need to be updated:

1. `expiresAt` should be `expires_at`
2. `wholeWord` should be `whole_word`, of type `boolean` instead of `string`

### PR DESCRIPTION
**Pull request by ayoayco**
fixes #725 to update the Filter interface

### CODE REVIEW

File: src/entities/filter.ts [hunk 1]
```diff
@@ -16,10 +16,10 @@ export interface Filter {
...
   context: FilterContext[];
-  /** When the filter should no longer be applied */
-  expiresAt?: string | null;
   /** Should matching entities in home and notifications be dropped by the server? */
   irreversible: boolean;
   /** Should the filter consider word boundaries? */
-  wholeWord: string;
+  whole_word: boolean;
+  /** When the filter should no longer be applied */
+  expires_at?: string | null;
```
Comment (neet) [inline src/entities/filter.ts:24]: See https://github.com/neet/masto.js/issues/725#issuecomment-1334107207

**Review by neet — CHANGES_REQUESTED** [review]

File: src/entities/filter.ts (hunk 1 above)
Comment (ayoayco) [reply src/entities/filter.ts]: Applied the requested change!

**Review by neet — APPROVED** [review]
